version: "3.8"

services:
  backend:
    build: .  # Build the Python backend from Dockerfile in the current directory
    ports:
      - "5000:5000"  # Expose backend API on port 5000
    environment:
      - DATABASE_URL=mysql://root:1721@db:3306/whey_protein  # Database connection
    depends_on:
      - db  # Start backend only after MySQL is running

  frontend:
    build: ./ShadFrontend/whey_protein  # Path to Next.js Dockerfile
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    environment:
      -
